import { describe, it, expect } from 'vitest';
import { render } from '@testing-library/preact';
import { Terminal } from './Terminal';

describe('Terminal', () => {
  it('renders the canonical postcard command', () => {
    const { container } = render(<Terminal />);
    const pre = container.querySelector('pre');
    expect(pre?.textContent).toContain('postcard --path ~/Desktop');
  });

  it('renders a $ prompt and a BIND follow-up line', () => {
    const { container } = render(<Terminal />);
    const pre = container.querySelector('pre');
    expect(pre?.textContent).toContain('$');
    expect(pre?.textContent).toMatch(/BIND http:\/\//);
  });

  it('uses monospace font on the code block', () => {
    const { container } = render(<Terminal />);
    const pre = container.querySelector('pre') as HTMLElement;
    expect(pre).toBeTruthy();
    // The class is generated by StyleX, so we just check the element exists
    // and that the content is wrapped in <code> for accessibility.
    expect(container.querySelector('pre > code')).toBeTruthy();
  });
});
